basic_settings:
  site_title: Vectgen Bio
  favicon_image: /assets/img/favicon.png

header_settings:
  logo_image: /assets/img/vectgen-logo-new.svg
  mobile_logo_image: /assets/img/vectgen-logo-new.svg
  # Choose a color for your header [blue, dark, light].
  theme: dark
  # If the page has a featured image, it turns transparent if allow_transparent is set to "yes".
  allow_transparent: "yes"

home_settings:
  # Choose a layout for your home page:
    # landing – an example landing page made using the Argon design system
    # blog – use your blog posts as the home page
  theme: landing

blog_settings:
  # Choose a format for your blog listings:
    # basic – a simple list of posts
    # narrow – a masonary grid of posts
    # grid – a full-width square grid of posts
  theme: basic
  # Should we display a narrow grid of other posts at the bottom of each blog post?
  read_more: "yes"

# Setup your navigation below – how to use the icons: 
  # 1. See all the icons available here https://demos.creative-tim.com/argon-design-system-pro/docs/1.0/foundation/icons.html
  # 2. Get the name of the icon e.g basket, then prefix with ni to make ni-basket. 
  # 3. Add a color of the icon - text-primary, text-success, text-info, text-danger, text-warning and text-default all work! 
menu_settings:
  menu_items:
    - title: 'Home'
      url: /
    - title: 'About Us'
      url: '/about'
    - title: 'Our Model'
      url: '/model'
    - title: 'Our Team'
      url: '/team'           
    - title: 'Contact'
      url: '/contact'

footer_settings:
  footer_tagline: Precision delivered. Hope restored.

contact_settings:
  form_action: 'https://formspree.io/f/mknpdezd'
  confirmation_url: '/thanks'
  email_subject: 'vectgenbio website contact'
  send_button_text: 'Send Message'
  phone_number: '+1 (919) 627-8118'
  street_address: 'Research Triangle Park, NC'
  email: 'info@vectgen.com<br/>investors@vectgen.com'

social_settings:
  facebook_url: 'https://facebook.com/VectgenBio'
  twitter_url: 'https://twitter.com/vectgenbio'
  instagram_url: ''
  youtube_url: ''
  vimeo_url: ''
  pinterest_url: ''
  tumblr_url: ''
  dribbble_url: ''
  behance_url: ''
  github_url: ''
  reddit_url: ''
  linkedin_url: 'https://www.linkedin.com/company/vectgenbio/'

authors:
  tom:
    name: Tom
    picture: /assets/img/faces/team-1.jpg
  jane:
    name: Jane
    picture: /assets/img/faces/team-4.jpg
  michael:
    name: Michael
    picture: /assets/img/faces/michael.jpg

advanced_settings:
  analytics_code: 
  header_js: 
  footer_js: 
